services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
      build:
        context: .
      env_file:
        - .env
      volumes:
        - ./src:/app/src
      expose:
        - 8000
      command: uvicorn src.main:app --proxy-headers --forwarded-allow-ips=* --host 0.0.0.0 --reload --port 8000

volumes:
  postgres_data:
